# CREATING ARRAYS

SINGLE DIMENSIONAL

In [4]:
import numpy as np

In [5]:
dd=np.array([1,2,3,4])
dd

array([1, 2, 3, 4])

In [6]:
dd.ndim

1

In [7]:
dd.shape

(4,)

MULTIDIMENSIONAL ARRAY

In [8]:
df=np.array([[1,2],[3,4],[5,6]])
df

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
df.ndim

2

In [12]:
df.shape

(3, 2)

# Arrays filled with constant values

In [13]:
np.zeros((2,3))#THE ARRAY FILLED WITH ZEROS CAN BE EITHER SINGLE OR MULTI DIMENSIONAL

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.ones((2,3))#THE ARRAY FILLED WITH ONES CAN BE EITHER SINGLE OR MULTI DIMENSIONAL

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones((2,3),dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
x1=5.4*np.ones((10))#an array filled with constant values are created
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

another way of creating an array filled with constant values


In [18]:
x2=np.full(10,5.4)#an array with 10 elements initialized with value 5.4 is created
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

way to fill an already created array with constant values

In [22]:
x3=np.zeros(5)
x3.fill(3.0)
x3

array([3., 3., 3., 3., 3.])

# ARRAY FILLED WITH INCREMENTAL SEQUENCE

In [23]:
np.arange(0,10,1)#returns 0 to 9 with incrementation of 1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(0,10,11)#np.linspace(startval,endval,no:ofpoints)(diff to np.arange is that it gives he endval)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# ARRAY FILLED WITH LOGARITHMIC SEQUENCE

In [25]:
np.logspace(0,3,5)#5 data points btw 10^0=1 to10^3=1000

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

# MESHGRID ARRAY

In [28]:
x=np.array([-1,0,1])
y=np.array([-2,0,2])
X,Y=np.meshgrid(x,y)
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [29]:
Y#MESHGRIDS ARE USED FOR PLOTTING RELATIO BTW TWO VARIABLES,COLOURPLOTS,CONTOURPLOTS ETC

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [30]:
Z=(X+Y)**2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

# CREATING UNINITIALIZED ARRAY

In [32]:
np.empty(3,dtype=np.float)

array([0., 0., 0.])

# CREATING MATRIX ARRAYS

In [33]:
np.identity(4)#creates a 4*4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.eye(4)#another way

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.eye(4,k=1)#use np.eye()we can offset the diagonals

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [36]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
np.diag(np.arange(0,20,4))#creates a one dimensional array of diagonal matrix

array([[ 0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  8,  0,  0],
       [ 0,  0,  0, 12,  0],
       [ 0,  0,  0,  0, 16]])

# INDEXING AND SLICING

In [44]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
a[0]#returns the first element of array 

0

In [42]:
a[-1]#returns the last element of the array

10

In [45]:
a[1:-1]#returns the second element to secondlast element

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[1:-1:2]#second to secondlast element with a step of 2 

array([1, 3, 5, 7, 9])

In [47]:
a[:6]#returns 0th to 5th element

array([0, 1, 2, 3, 4, 5])

In [48]:
a[-5:]#returns the seventh element(sixth )to last

array([ 6,  7,  8,  9, 10])

In [49]:
a[::-1]#returns the array in reverse order

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [50]:
a[::-2]#returns the arrray in reverseorder with a step of 2

array([10,  8,  6,  4,  2,  0])

# MULTIDIMENSIONAL ARRAY

In [54]:
f=lambda m,n:n+10*m#two arguments n and m returns(n+10*m)

In [60]:
a=np.fromfunction(f,(6,6),dtype=int)#eg for (2,1) m=1,n=0;f=0+10*1=10;
                                    # for (5,3)m=4,n=2;f=2+10*4=42
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [61]:
a.shape

(6, 6)

In [62]:
a[:,0]#returns first column

array([ 0, 10, 20, 30, 40, 50])

In [63]:
a[0,:]#returns th first row

array([0, 1, 2, 3, 4, 5])

In [65]:
a[:3,:3]#returns the upper half diagonal block

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [66]:
a[3:,:3]#returns the lower left diagonal block

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [67]:
a[:3,3:]#returns upper right diagonal block

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25]])

In [68]:
a[3:,3:]#return the lower right diagonal block

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [70]:
a[::2,::2]#every second element starting from 0,0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [72]:
a[::1,::2]#from every row returns every second  column

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

In [73]:
a[::2,::1]#from every column returns every second row

array([[ 0,  1,  2,  3,  4,  5],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

In [74]:
a[1::2,1::3]#every second row and third column starting from 1,1

array([[11, 14],
       [31, 34],
       [51, 54]])

In [75]:
a[[1,2],[3,3]]#returns(1,3)&(2,3)nb:indexing starts from (0,0)

array([13, 23])