# ARITHMETIC OPERATIONS

In [5]:
import numpy as np

In [7]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [9]:
y=np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [10]:
x+y


array([[ 6,  8],
       [10, 12]])

In [11]:
x-y

array([[-4, -4],
       [-4, -4]])

In [12]:
x*y

array([[ 5, 12],
       [21, 32]])

In [13]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [14]:
x**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [15]:
5**x

array([[  5,  25],
       [125, 625]], dtype=int32)

In [21]:
z=np.array([[2,3]])

In [22]:
zz=np.concatenate([z,z],axis=0)
zz

array([[2, 3],
       [2, 3]])

In [24]:
zz=np.concatenate([z,z],axis=1)
zz

array([[2, 3, 2, 3]])

In [28]:
 import seaborn as sns