# BASIC ATTRIBUTES OF NUMPY

In [17]:
import numpy as np
data=np.array([[1,2],[3,4],[5,6]])
type(data)#THE DATASTRUCTURE IS NDARRAY CLASS

numpy.ndarray

In [18]:
data=np.array([[1,2],[3,4],[5,6]],dtype=np.int32)#since arrays are homogenous we can set a datatype

In [8]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
data.ndim#prints out the number of dimensions or axis

2

In [10]:
data.shape#it will return a tuple containing number of elements in each axis of array(rows,columns) 

(3, 2)

In [11]:
data.size#returns the number of elements in the array

6

In [12]:
data.dtype#returns the datatype of elements in the array

dtype('int32')

In [13]:
data.nbytes#number of bytes used to store the data

24

# DATATYPES IN NUMPY

In [23]:
np.array([1,2,3,4],dtype=np.int)#creating an integer array

array([1, 2, 3, 4])

In [20]:
np.array([1,2,3,4],dtype=np.float)#creating a float array

array([1., 2., 3., 4.])

In [21]:
np.array([1,2,3,4],dtype=np.complex)#creating an array of complex numbers

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

# #TYPE CASTING

In [24]:
data=np.array([1,2,3,4],dtype=np.float)#int to float
data

array([1., 2., 3., 4.])

In [25]:
data.dtype

dtype('float64')

In [26]:
data=np.array(data,np.int)#converting the float array back to int
data

array([1, 2, 3, 4])

In [27]:
data.dtype

dtype('int32')

ASTYPE ATTRIBUTE FOR TYPECASTING

In [28]:
data=np.array([1,2,3,4],dtype=np.float)
data

array([1., 2., 3., 4.])

In [29]:
data.astype(np.int)

array([1, 2, 3, 4])

During computation the datatype might get promoted from one type to other

In [31]:
d1=np.array([1,2,3,4],dtype=np.float)
d2=np.array([1,2,3,4],dtype=np.complex)
d1+d2#the result gets automatically typecasted to complex

array([2.+0.j, 4.+0.j, 6.+0.j, 8.+0.j])

Sometimes we have to essentially set a datatype for computation for example

In [32]:
df=np.sqrt(np.array([-1,0,1]))#it will return an error since we didnt set the appropriate dtype

C:\Users\hp\Anaconda3\anaconda2020\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [35]:
df=np.sqrt(np.array([-1,0,1],dtype=complex))#Hurray now the code worked
df

array([0.+1.j, 0.+0.j, 1.+0.j])

In [36]:
df.real#will return the  real parts

array([0., 0., 1.])

In [37]:
df.imag#will return the imaginary part

array([1., 0., 0.])

# Row major and column major

In [44]:
d=np.array([[1,2],[3,4],[5,6]],order='C')#order='C' for row major format(in c and c++ this is the format)


In [45]:
d.shape

(3, 2)

In [46]:
f=np.array([[1,2],[3,4],[5,6]],order='F')#order='F' for column major format(in Fotran)

In [47]:
f.shape

(3, 2)