# VIEWS 

In [2]:
import numpy as np

In [3]:
f=lambda m,n:n+10*m
a=np.fromfunction(f,(6,6),dtype=int)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [4]:
b=a[1:5,1:5]
b

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [5]:
b[:,:]=0#all elements of b is repplaced with 0

In [6]:
a#change in b will be reflected in a also(since both arrays refer to the same data in memory)

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [7]:
c=b[:,:].copy()# a copy is created to avoid mutation
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
c.fill(5)#now c array is filled with value 5.Will it cause any change in the b array?Lets check
c

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
b#NOP! thats the merit of copy()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Fancy Indexing And Boolean Valued Indexing

In [10]:
a=np.linspace(0,10,11)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
a[np.array([0,2,4])]#using fancy indexing an array can be indexed with other numpy array

array([0., 2., 4.])

In [12]:
a[np.array([0,2,4,11])]#oops this will return an error 

IndexError: index 11 is out of bounds for axis 0 with size 11

In [ ]:
a[[0,2,4]]#same fancy indexing can be accomplished with a python list

# BOOL-VALUED INDEXING

In [ ]:
a>4

In [ ]:
a[a>4]#from the array only the true values will be selected

In [ ]:
a=np.arange(10)
a

In [ ]:
indices=[2,4,6]

In [ ]:
b=a[indices]
b

In [ ]:
b[0]=-1#this doesnt affect a
b

In [ ]:
a

In [ ]:
a[indices]=-1
a

In [ ]:
a=np.arange(10)
a[a>5]=-1
a

# RESHAPING AND RESIZING

In [15]:
data=np.array([[1,2],[3,4]])# a 2*2 array is created
data

array([[1, 2],
       [3, 4]])

In [16]:
np.reshape(data,(1,4))#now data is reshaped into a 1*4 array

array([[1, 2, 3, 4]])

In [17]:
data.reshape(4)#this will also return the same output

array([1, 2, 3, 4])

In [21]:
arr=np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr.flatten()#collapses the axis of the array into a single dimensional(it will return acopy)

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [23]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr.ravel()#it will also do the same but it returns a view

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [26]:
arr.reshape(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
data=np.arange(1,10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
data.ndim

1

In [31]:
column=data[:,np.newaxis]#creates a new axis,the dimension changes from 1 to2
column


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [36]:
column.ndim

2

In [32]:
row=data[np.newaxis,:]
row

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
row.ndim

2

In [39]:
np.expand_dims(data,axis=1)#axis specifies the location among existing axis where new_axis is to be inserted

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [40]:
np.expand_dims(data,axis=0)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# VSTACK AND HSTACK

In [48]:
f=lambda m,n:n+10*m#two arguments n and m returns(n+10*m)
data=np.fromfunction(f,(6,6),dtype=int)#eg for (2,1) m=1,n=0;f=0+10*1=10;
                                    # for (5,3)m=4,n=2;f=2+10*4=42
data   

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [50]:
a1=data[:3,:3]#returns the upper half diagonal block
a1

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [51]:
a2=data[3:,:3]#returns the lower left diagonal block
a2

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [52]:
a3=data[:3,3:]#returns upper right diagonal block
a3

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25]])

In [53]:
a4=data[3:,3:]#return the lower right diagonal block
a4

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [55]:
data=np.hstack((a1,a2,a3,a4))#here the arrays are horizontally stacked
data

array([[ 0,  1,  2, 30, 31, 32,  3,  4,  5, 33, 34, 35],
       [10, 11, 12, 40, 41, 42, 13, 14, 15, 43, 44, 45],
       [20, 21, 22, 50, 51, 52, 23, 24, 25, 53, 54, 55]])

In [56]:
data=np.vstack((a1,a2,a3,a4))#here the arrays are vertically stacked
data

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42],
       [50, 51, 52],
       [ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])